apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments-container
          image: acr96.azurecr.io/payments:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: JWT_ISSUER
            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: JWT_AUDIENCE
            - name: Microservices__GameUrl
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: GAME_URL
            - name: Microservices__UserUrl
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: USER_URL
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: ENVIRONMENT

            - name: ConnectionStrings__TechDb
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: connectionstring
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: jwtkey
            - name: Credentials__Email
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: adminemail
            - name: Credentials__Password
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: adminpassword
            - name: ElasticSettings__ApiKey
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: elasticapikey
            - name: ElasticSettings__CloudId
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: elasticcloudid
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: newrelickey
      imagePullSecrets:
        - name: credentials
